spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://prd6.hbjk.com.cn:3306/subway_db_v2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: hbj_2012_writer
    password: writer_2012_hbj
  data:
    mongodb:
      host: 116.62.4.123
      port: 27017
      database: subway
      username: hbj_2020_writer
      password: writer_2020_hbj
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  redis:
    database: 0
    host: 116.62.4.123
    port: 6379
    password: landfun2012
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
logging:
  config: classpath:logback.xml

server:
  port: 18088
  contextPath: /subway_api
host-name: prd9