spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gjol?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root	
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: taokoo
    pool:
      max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 3 # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）
logging:
  config: classpath:logback.xml

server:
  port: 8868
  contextPath: /gjol
host-name: taokoo

imgPath=C:\\Users\\EDZ\\Desktop